/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import clases.Cuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author yescobar7
 */

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Cuenta c; 
    public Principal() {
        initComponents();
        cmdCrear.setEnabled(true);
        cmdIngresar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdActualizar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdCuentaNueva.setEnabled(false);
        cmdLimpiar.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        txtNumeroID = new javax.swing.JTextField();
        txtSaldoActual = new javax.swing.JTextField();
        cmdCrear = new javax.swing.JButton();
        cmdCuentaNueva = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtIngresar = new javax.swing.JTextField();
        cmdIngresar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtRetirar = new javax.swing.JTextField();
        cmdRetirar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cmdMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        cmdLimpiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtInteres = new javax.swing.JTextField();
        cmdActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Cuenta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 80, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cuenta"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Numero Cuenta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Numero Identificacion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Saldo Actual");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        txtNumeroCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroCuentaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 200, -1));

        txtNumeroID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroIDKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumeroID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 200, -1));

        txtSaldoActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoActualKeyTyped(evt);
            }
        });
        jPanel1.add(txtSaldoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 210, -1));

        cmdCrear.setText("Crear Cuenta");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        cmdCuentaNueva.setText("Crear Nueva Cuenta");
        cmdCuentaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCuentaNuevaActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCuentaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 410, 190));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Saldo"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngresarKeyTyped(evt);
            }
        });
        jPanel2.add(txtIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, -1));

        cmdIngresar.setText("Ingresar");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 210, 100));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Retirar Saldo"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRetirar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRetirarKeyTyped(evt);
            }
        });
        jPanel3.add(txtRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, -1));

        cmdRetirar.setText("Retirar");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 210, 100));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtMostrar.setEditable(false);
        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 330, 130));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 370, 220));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Interes"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInteres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInteresKeyTyped(evt);
            }
        });
        jPanel4.add(txtInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, -1));

        cmdActualizar.setText("Actualizar");
        cmdActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 210, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
    long numero_cuenta,id;
        double saldo;
        if (txtNumeroCuenta.getText().trim().isEmpty()||txtNumeroID.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this,"Ingrese Datos ","ERROR",JOptionPane.ERROR_MESSAGE);
        txtNumeroCuenta.requestFocusInWindow();
        }
        else{ 
        if (txtSaldoActual.getText().trim().isEmpty()){
        numero_cuenta=Long.parseLong(txtNumeroCuenta.getText());
        id=Long.parseLong(txtNumeroID.getText()); 
        c= new Cuenta (numero_cuenta, id);
        JOptionPane.showMessageDialog(this,"Cuenta Creada Exitosamente Con Saldo En 0");
        }else{
        numero_cuenta=Long.parseLong(txtNumeroCuenta.getText());
        id=Long.parseLong(txtNumeroID.getText());
        saldo=Double.parseDouble(txtSaldoActual.getText());
        
        c= new Cuenta (numero_cuenta, id, saldo);
        JOptionPane.showMessageDialog(this,"Cuenta Creada Exitosamente");
        }
        cmdCrear.setEnabled(false);
        cmdIngresar.setEnabled(true);
        cmdRetirar.setEnabled(true);
        cmdActualizar.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdCuentaNueva.setEnabled(true);
        cmdLimpiar.setEnabled(true);
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
    double aux;
    if(txtIngresar.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(this, "Ingrese saldo por favor", "Error", JOptionPane.ERROR_MESSAGE);
    txtIngresar.requestFocusInWindow();
    }
    else{
    aux=Integer.parseInt(txtIngresar.getText());
    c.ingresar(aux);
    JOptionPane.showMessageDialog(this,"Ingreso Exitosamente");
    txtIngresar.setText("");
    }
    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
    String aux;
    aux=c.mostrar();
    txtMostrar.append(aux);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed
    double aux1,aux2;
    aux1=Integer.parseInt(txtRetirar.getText());
    aux2=c.getSaldo_actual();
    if(txtRetirar.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(this, "Digite el dinero a retirar", "Error", JOptionPane.ERROR_MESSAGE);
    txtRetirar.requestFocusInWindow();        
    }
    else if(aux1>aux2){
    JOptionPane.showMessageDialog(this,"No Puede Retirar Esta Cantidad de dinero \n"
                    + "Saldo Insuficiente","ERROR",JOptionPane.ERROR_MESSAGE);
    }else{
    c.retirar(aux1);
    JOptionPane.showMessageDialog(this,"Retiro Exitoso");
    txtRetirar.setText("");
    }
    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void cmdActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarActionPerformed
    double aux;
    if(txtInteres.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(this, "Digite el interes por favor", "Error", JOptionPane.ERROR_MESSAGE);
    txtInteres.requestFocusInWindow();
    }
    else{
    try{
    aux=Double.parseDouble(txtInteres.getText());
    c.actualizar_saldo(aux);
    JOptionPane.showMessageDialog(this,"Interes Aplicado");
    txtInteres.setText("");
    }catch(NumberFormatException e){}
    }
    }//GEN-LAST:event_cmdActualizarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
    txtNumeroCuenta.setText("");
    txtNumeroID.setText("");
    txtSaldoActual.setText("");
    txtIngresar.setText("");
    txtRetirar.setText("");
    txtInteres.setText("");
    txtMostrar.setText("");
    cmdCrear.setEnabled(true);
    cmdIngresar.setEnabled(false);
    cmdRetirar.setEnabled(false);
    cmdActualizar.setEnabled(false);
    cmdMostrar.setEnabled(false);
    cmdCuentaNueva.setEnabled(false);
    cmdLimpiar.setEnabled(true);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdCuentaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCuentaNuevaActionPerformed
    txtNumeroCuenta.setText("");
        txtNumeroID.setText("");
        txtSaldoActual.setText("");
        txtIngresar.setText("");
        txtRetirar.setText("");
        txtInteres.setText("");
        txtMostrar.setText("");
        c=null;
        txtNumeroCuenta.requestFocusInWindow();
        cmdCrear.setEnabled(true);
        cmdIngresar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdActualizar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdCuentaNueva.setEnabled(false);
        cmdLimpiar.setEnabled(false);
    }//GEN-LAST:event_cmdCuentaNuevaActionPerformed

    private void txtNumeroCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroCuentaKeyTyped
    char c=evt.getKeyChar(); 
    if(!Character.isDigit(c)) { 
    getToolkit().beep(); 
    evt.consume(); 
    }
    }//GEN-LAST:event_txtNumeroCuentaKeyTyped

    private void txtNumeroIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroIDKeyTyped
    char c=evt.getKeyChar(); 
    if(!Character.isDigit(c)) { 
    getToolkit().beep(); 
    evt.consume(); 
    }
    }//GEN-LAST:event_txtNumeroIDKeyTyped

    private void txtSaldoActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoActualKeyTyped
    char c=evt.getKeyChar(); 
    if(!Character.isDigit(c)) { 
    getToolkit().beep(); 
    evt.consume(); 
    }
    }//GEN-LAST:event_txtSaldoActualKeyTyped

    private void txtInteresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInteresKeyTyped
    char c=evt.getKeyChar(); 
    if(!Character.isDigit(c)) { 
    getToolkit().beep(); 
    evt.consume(); 
    }
    }//GEN-LAST:event_txtInteresKeyTyped

    private void txtIngresarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresarKeyTyped
    char c=evt.getKeyChar(); 
    if(!Character.isDigit(c)) { 
    getToolkit().beep(); 
    evt.consume(); 
    }
    }//GEN-LAST:event_txtIngresarKeyTyped

    private void txtRetirarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetirarKeyTyped
    char c=evt.getKeyChar(); 
    if(!Character.isDigit(c)) { 
    getToolkit().beep(); 
    evt.consume(); 
    }
    }//GEN-LAST:event_txtRetirarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActualizar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdCuentaNueva;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIngresar;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextArea txtMostrar;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtNumeroID;
    private javax.swing.JTextField txtRetirar;
    private javax.swing.JTextField txtSaldoActual;
    // End of variables declaration//GEN-END:variables
}
